FROM node:22

COPY ./api /home/api
WORKDIR /home/api

#RUN apt-get -y install iptables cron
RUN mkdir -p test/reports coverage

CMD echo "NODE_ENV = $NODE_ENV"; \
    npm ci && \
    echo "Mocha version:" && npx mocha --version || true && \
    node -e "try{console.log('mochawesome version:', require('mochawesome/package.json').version)}catch(e){console.log('mochawesome not found')};" && \
    npm run build:test && \
    npm test || true; \
    echo "Contents of test/reports inside container:" && ls -la test/reports || true; \
    echo "Contents of coverage inside container:" && ls -la coverage || true;
# Utile pour debugguer et rentrer dans le conteneur si celui-ci n'est plus OK
#sleep infinity;
