FROM node:16.15.1

COPY ./api /home/api
WORKDIR /home/api

CMD echo "$NODE_ENV"; && \
    npm ci --production=false && \
    if [ "$NODE_ENV" = "production" ] || [ "$NODE_ENV" = "recette" ] || [ "$NODE_ENV" = "test" ]; then \
        npm run build:production && \ 
	    npm run start:production; \
    else \
        npm run start; \
    fi; 
