services:
  #api:
  #  restart: unless-stopped
  #  expose:
  #    - "8080"
  #  networks:
  #    mobiville_network:
  #      ipv4_address: 173.0.0.20
  #  depends_on:
  #    - "db"
  #  environment:
  #    - DATABASE_URL=${DATABASE_URL}
  #  stdin_open: true

  db:
    image: postgres:10.4
    restart: always
    cpus: 2.0
    mem_limit: 4G
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Paris
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=2GB"
      - "-c"
      - "effective_cache_size=6GB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "checkpoint_completion_target=0.7"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=4"
      - "-c"
      - "effective_io_concurrency=2"
      - "-c"
      - "work_mem=5242kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "max_worker_processes=4"
      - "-c"
      - "max_parallel_workers_per_gather=2"
      - "-c"
      - "max_parallel_workers=4"

  dbCA:
    image: postgres:10.4
    restart: always
    cpus: 2.0
    mem_limit: 4G
    ports:
      - "${POSTGRES_PORT_CA}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=Europe/Paris
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=2GB"
      - "-c"
      - "effective_cache_size=6GB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "checkpoint_completion_target=0.7"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=4"
      - "-c"
      - "effective_io_concurrency=2"
      - "-c"
      - "work_mem=5242kB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
      - "-c"
      - "max_worker_processes=4"
      - "-c"
      - "max_parallel_workers_per_gather=2"
      - "-c"
      - "max_parallel_workers=4"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

#networks:
#  mobiville_network:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 173.0.0.0/16
