services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: fxmontigny@gmail.com
      POSTGRES_USER: fxmontigny
      PGADMIN_DEFAULT_PASSWORD: azerty95
    ports:
      - "5050:80"
    restart: unless-stopped
  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
