FROM node:12.18.4

COPY ./api /home/api
WORKDIR /home/api

#RUN apt-get -y install iptables cron

CMD (which yarn || npm i -g yarn@1.15.2) && \
    echo "NODE_ENV = $NODE_ENV"; \
    yarn install --production=false && \
    yarn build:test && \ 
    yarn start:production & \
    yarn test;
# Utile pour debugguer et rentrer dans le conteneur si celui-ci n'est plus OK
#sleep infinity;
