FROM node:16.15.1

COPY ./front /home/front
WORKDIR /home/front

#RUN apt-get -y install iptables cron

CMD npm install --include=dev && \
    npm start && \
    npm run e2e;
# Utile pour debugguer et rentrer dans le conteneur si celui-ci n'est plus OK
#sleep infinity;
