export const HEADER_COLUMN_NAMES = ['I_ELST', 'C_TUS', 'NATAFF', 'PERIODE', 'NBAFF']

export const TAG_JURIDICTION_ID_COLUMN_NAME = 'I_ELST'
export const TAG_JURIDICTION_VALUE_COLUMN_NAME = 'NOM_COMPTEUR'