/**
 * Fonction recodée non affiché dans A-JUST pour le TJ
 */
export const FUNCTIONS_ONLY_FOR_DDG_EXTRACTOR = [
  {
    category_label: "Magistrat",
    label: "VICE-PRÉSIDENT PLACÉ ADDITIONNEL",
    code: "VP PLACÉ ADDITIONNEL",
    position: "Placé",
    category_detail: "M-PLAC-ADD",
    recodedFunction: "Magistrat placé ADD",
  },
  {
    category_label: "Magistrat",
    label: "JUGE PLACÉ ADDITIONNEL",
    code: "J. PLACÉ ADDITIONNEL",
    position: "Placé",
    category_detail: "M-PLAC-ADD",
    recodedFunction: "Magistrat placé ADD",
  },
  {
    category_label: "Magistrat",
    label: "VICE-PRÉSIDENT PLACÉ SUBSTITUTION",
    code: "VP PLACÉ SUBSTITUTION",
    position: "Placé",
    category_detail: "M-PLAC-SUB",
    recodedFunction: "Magistrat placé SUB",
  },
  {
    category_label: "Magistrat",
    label: "JUGE PLACÉ SUBSTITUTION",
    code: "J. PLACÉ SUBSTITUTION",
    position: "Placé",
    category_detail: "M-PLAC-SUB",
    recodedFunction: "Magistrat placé SUB",
  },
  {
    category_label: "Greffe",
    label: "A PLACÉ ADDITIONNEL",
    code: "A PLACÉ ADDITIONNEL",
    position: "Placé",
    category_detail: "F-PLAC-ADD",
    recodedFunction: "Fonctionnaire A-B-CBUR placé ADD",
  },
  {
    category_label: "Greffe",
    label: "B GREFFIER PLACÉ ADDITIONNEL",
    code: "B GREF  PLACÉ ADDITIONNEL",
    position: "Placé",
    category_detail: "F-PLAC-ADD",
    recodedFunction: "Fonctionnaire A-B-CBUR placé ADD",
  },
  {
    category_label: "Greffe",
    label: "B PLACÉ ADDITIONNEL",
    code: "B PLACÉ ADDITIONNEL",
    position: "Placé",
    category_detail: "F-PLAC-ADD",
    recodedFunction: "Fonctionnaire A-B-CBUR placé ADD",
  },
  {
    category_label: "Greffe",
    label: "CB PLACÉ ADDITIONNEL",
    code: "CB PLACÉ ADDITIONNEL",
    position: "Placé",
    category_detail: "F-PLAC-ADD",
    recodedFunction: "Fonctionnaire A-B-CBUR placé ADD",
  },
  {
    category_label: "Greffe",
    label: "CT PLACÉ ADDITIONNEL",
    code: "CT PLACÉ ADDITIONNEL",
    position: "Placé",
    category_detail: "F-PLAC-ADD",
    recodedFunction: "Fonctionnaire CTECH placé ADD",
  },
  {
    category_label: "Greffe",
    label: "A PLACÉ SUBSTITUTION",
    code: "A PLACÉ SUBSTITUTION",
    position: "Placé",
    category_detail: "F-PLAC-SUB",
    recodedFunction: "Fonctionnaire A-B-CBUR placé SUB",
  },
  {
    category_label: "Greffe",
    label: "B GREFFIER PLACÉ SUBSTITUTION",
    code: "B GREF  PLACÉ SUBSTITUTION",
    position: "Placé",
    category_detail: "F-PLAC-SUB",
    recodedFunction: "Fonctionnaire A-B-CBUR placé SUB",
  },
  {
    category_label: "Greffe",
    label: "B PLACÉ SUBSTITUTION",
    code: "B PLACÉ SUBSTITUTION",
    position: "Placé",
    category_detail: "F-PLAC-SUB",
    recodedFunction: "Fonctionnaire A-B-CBUR placé SUB",
  },
  {
    category_label: "Greffe",
    label: "CB PLACÉ SUBSTITUTION",
    code: "CB PLACÉ SUBSTITUTION",
    position: "Placé",
    category_detail: "F-PLAC-SUB",
    recodedFunction: "Fonctionnaire A-B-CBUR placé SUB",
  },
  {
    category_label: "Greffe",
    label: "CT PLACÉ SUBSTITUTION",
    code: "CT PLACÉ SUBSTITUTION",
    position: "Placé",
    category_detail: "F-PLAC-SUB",
    recodedFunction: "Fonctionnaire CTECH placé SUB",
  },
  {
    category_label: "Autour du Juge",
    label: "JURISTE ASSISTANT siège Autres",
    code: "JA Siège autres",
    position: "Contractuel",
    category_detail: "C",
    recodedFunction: "JURISTE AS siège Autres",
  },
  {
    category_label: "Autour du Juge",
    label: "JURISTE ASSISTANT Pôle social",
    code: "JA Pôle social",
    position: "Contractuel",
    category_detail: "C",
    recodedFunction: "JURISTE AS Pôle social",
  },
  {
    category_label: "Autour du Juge",
    label: "JURISTE ASSISTANT Parquet",
    code: "JA Parquet",
    position: "Contractuel",
    category_detail: "C",
    recodedFunction: "JURISTE AS Parquet",
  },
  {
    category_label: "Autour du Juge",
    label: "JURISTE ASSISTANT Vif",
    code: "JA VIF",
    position: "Contractuel",
    category_detail: "C",
    recodedFunction: "CONT A JP Autour du Juge",
  },
  {
    category_label: "Autour du Juge",
    label: "CONTRACTUEL A JUSTICE DE PROXIMITE",
    code: "JA JP",
    position: "Contractuel",
    category_detail: "C",
    recodedFunction: "CONT A JP Autour du Juge",
  },
  {
    category_label: "Autour du Juge",
    label: "CONTRACTUEL A JUSTICE DE PROXIMITE",
    code: "CONT A JP Autour du magistrat",
    position: "Contractuel",
    category_detail: "C",
    recodedFunction: "CONT A JP Autour du Juge",
  },
  {
    category_label: "Autour du Juge",
    label: "CONTRACTUEL B JUSTICE DE PROXIMITE",
    code: "CONT B JP Autour du magistrat",
    position: "Contractuel",
    category_detail: "C",
    recodedFunction: "",
  },
  {
    category_label: "Autour du Juge",
    label: "CONTRACTUEL C JUSTICE DE PROXIMITE",
    code: "CONT C JP Autour du magistrat",
    position: "Contractuel",
    category_detail: "C",
    recodedFunction: "",
  },
];
