/**
 * Fonction recodée non affiché dans A-JUST pour le TJ
 */
export const FUNCTIONS_ONLY_FOR_DDG_EXTRACTOR = [
  {
    category_label: 'Magistrat',
    label: 'VICE-PRÉSIDENT PLACÉ ADDITIONNEL',
    code: 'VP PLACÉ ADDITIONNEL',
    position: 'Placé',
    category_detail: 'M-PLAC-ADD',
    recodedFunction: 'Magistrat placé ADD',
    rank: 21,
  },
  {
    category_label: 'Magistrat',
    label: 'JUGE PLACÉ ADDITIONNEL',
    code: 'J. PLACÉ ADDITIONNEL',
    position: 'Placé',
    category_detail: 'M-PLAC-ADD',
    recodedFunction: 'Magistrat placé ADD',
    rank: 22,
  },
  {
    category_label: 'Magistrat',
    label: 'VICE-PRÉSIDENT PLACÉ SUBSTITUTION',
    code: 'VP PLACÉ SUBSTITUTION',
    position: 'Placé',
    category_detail: 'M-PLAC-SUB',
    recodedFunction: 'Magistrat placé SUB',
    rank: 21,
  },
  {
    category_label: 'Magistrat',
    label: 'JUGE PLACÉ SUBSTITUTION',
    code: 'J. PLACÉ SUBSTITUTION',
    position: 'Placé',
    category_detail: 'M-PLAC-SUB',
    recodedFunction: 'Magistrat placé SUB',
    rank: 22,
  },
  {
    category_label: 'Greffe',
    label: 'A PLACÉ ADDITIONNEL',
    code: 'A PLACÉ ADDITIONNEL',
    position: 'Placé',
    category_detail: 'F-PLAC-ADD',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé ADD',
    rank: 7,
  },
  {
    category_label: 'Greffe',
    label: 'B GREFFIER PLACÉ ADDITIONNEL',
    code: 'B GREF  PLACÉ ADDITIONNEL',
    position: 'Placé',
    category_detail: 'F-PLAC-ADD',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé ADD',
    rank: 8,
  },
  {
    category_label: 'Greffe',
    label: 'B PLACÉ ADDITIONNEL',
    code: 'B PLACÉ ADDITIONNEL',
    position: 'Placé',
    category_detail: 'F-PLAC-ADD',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé ADD',
    rank: 9,
  },
  {
    category_label: 'Greffe',
    label: 'CB PLACÉ ADDITIONNEL',
    code: 'CB PLACÉ ADDITIONNEL',
    position: 'Placé',
    category_detail: 'F-PLAC-ADD',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé ADD',
    rank: 10,
  },
  {
    category_label: 'Greffe',
    label: 'CT PLACÉ ADDITIONNEL',
    code: 'CT PLACÉ ADDITIONNEL',
    position: 'Placé',
    category_detail: 'F-PLAC-ADD',
    recodedFunction: 'Fonctionnaire CTECH placé ADD',
    rank: 11,
  },
  {
    category_label: 'Greffe',
    label: 'A PLACÉ SUBSTITUTION',
    code: 'A PLACÉ SUBSTITUTION',
    position: 'Placé',
    category_detail: 'F-PLAC-SUB',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé SUB',
    rank: 7,
  },
  {
    category_label: 'Greffe',
    label: 'B GREFFIER PLACÉ SUBSTITUTION',
    code: 'B GREF  PLACÉ SUBSTITUTION',
    position: 'Placé',
    category_detail: 'F-PLAC-SUB',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé SUB',
    rank: 8,
  },
  {
    category_label: 'Greffe',
    label: 'B PLACÉ SUBSTITUTION',
    code: 'B PLACÉ SUBSTITUTION',
    position: 'Placé',
    category_detail: 'F-PLAC-SUB',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé SUB',
    rank: 9,
  },
  {
    category_label: 'Greffe',
    label: 'CB PLACÉ SUBSTITUTION',
    code: 'CB PLACÉ SUBSTITUTION',
    position: 'Placé',
    category_detail: 'F-PLAC-SUB',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé SUB',
    rank: 10,
  },
  {
    category_label: 'Greffe',
    label: 'CT PLACÉ SUBSTITUTION',
    code: 'CT PLACÉ SUBSTITUTION',
    position: 'Placé',
    category_detail: 'F-PLAC-SUB',
    recodedFunction: 'Fonctionnaire CTECH placé SUB',
    rank: 11,
  }, // JA
  {
    category_label: 'Autour du magistrat',
    label: 'JURISTE ASSISTANT pôle Social',
    code: 'JA Social',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ Social',
    rank: 3,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'JURISTE ASSISTANT JA Siège autres',
    code: 'JA Siège autres',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ Siège autres',
    rank: 3,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'JURISTE ASSISTANT Parquet',
    code: 'JA Parquet',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ Parquet',
    rank: 3,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'JURISTE ASSISTANT JAP',
    code: 'JA JAP',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ JAP',
    rank: 3,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'JURISTE ASSISTANT JE',
    code: 'JA JE',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ JE',
    rank: 3,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'JURISTE ASSISTANT JI',
    code: 'JA JI',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ JI',
    rank: 3,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'JURISTE ASSISTANT JLD',
    code: 'JA JLD',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ JLD',
    rank: 3,
  }, 
  // Att. Justice
  {
    category_label: 'Autour du magistrat',
    label: 'ATTACHÉ DE JUSTICE pôle Social',
    code: 'Att. J Social',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ Social',
    rank: 2,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'ATTACHÉ DE JUSTICE JA Siège autres',
    code: 'Att. J Siège autres',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ Siège autres',
    rank: 2,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'ATTACHÉ DE JUSTICE Parquet',
    code: 'Att. J Parquet',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ Parquet',
    rank: 2,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'ATTACHÉ DE JUSTICE JAP',
    code: 'Att. J JAP',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ JAP',
    rank: 2,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'ATTACHÉ DE JUSTICE JE',
    code: 'Att. J JE',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ JE',
    rank: 2,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'ATTACHÉ DE JUSTICE JI',
    code: 'Att. J JI',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ JI',
    rank: 2,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'ATTACHÉ DE JUSTICE JLD PÉNAL',
    code: 'Att. J JLD PÉNAL',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ JLD PÉNAL',
    rank: 2,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'ATTACHÉ DE JUSTICE SIEGE ASSISES',
    code: 'Att. J Siege Assises',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ SIEGE ASSISES',
    rank: 2,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'ATTACHÉ DE JUSTICE SIEGE CCD',
    code: 'Att. J Siege CCD',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'Att.J SIEGE CCD',
    rank: 2,
  },
  {
    // CONT A JP
    category_label: 'Autour du magistrat',
    label: 'CONTRACTUEL A JUSTICE DE PROXIMITE',
    code: 'CONT A JP Siège',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'CONT A JP Siège',
    rank: 5,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'CONTRACTUEL A JUSTICE DE PROXIMITE',
    code: 'CONT A JP Parquet',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'CONT A JP Parquet',
    rank: 5,
  },
  {
    category_label: 'Greffe',
    label: 'CONTRACTUEL A JUSTICE DE PROXIMITE',
    code: 'CONT A JP Siège',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'CONT A JP Siège',
    rank: 19,
  },
  {
    category_label: 'Greffe',
    label: 'CONTRACTUEL A JUSTICE DE PROXIMITE',
    code: 'CONT A JP Parquet',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'CONT A JP Parquet',
    rank: 19,
  },
  {
    //CONT A
    category_label: 'Greffe',
    label: 'CONTRACTUEL A',
    code: 'CONT A VIF Siège',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'CONT A VIF Siège',
    rank: 13,
  },
  {
    category_label: 'Greffe',
    label: 'CONTRACTUEL A',
    code: 'CONT A VIF Parquet',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'CONT A VIF Parquet',
    rank: 13,
  },
  {
    category_label: 'Greffe',
    label: 'CONTRACTUEL A',
    code: 'CONT A Autres',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'Fonctionnaire A-B-CBUR',
    rank: 13,
  },
  {
    category_label: 'Greffe',
    label: 'DSGJ PLACÉ ADDITIONNEL',
    code: 'DSGJ PLACÉ ADDITIONNEL',
    rank: 10,
    position: 'Placé',
    category_detail: 'F-PLAC-ADD',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé ADD',
  },
  {
    category_label: 'Greffe',
    label: 'DSGJ PLACÉ SUBSTITUTION',
    code: 'DSGJ PLACÉ SUBSTITUTION',
    rank: 10,
    position: 'Placé',
    category_detail: 'F-PLAC-SUB',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé SUB',
  },
]

/**
 * Fonction recodée non affiché dans A-JUST pour le CA
 */
export const FUNCTIONS_ONLY_FOR_DDG_EXTRACTOR_CA = [
  {
    category_label: 'Magistrat',
    label: 'VICE-PRÉSIDENT PLACÉ ADDITIONNEL',
    code: 'VPP ADDITIONNEL',
    position: 'Placé',
    category_detail: 'M-PLAC-ADD',
    recodedFunction: 'Magistrat placé ADD',
    rank: 6,
  },
  {
    category_label: 'Magistrat',
    label: 'VICE-PRÉSIDENT PLACÉ DE SUBSTITUTION',
    code: 'VPP SUBSTITUTION',
    position: 'Placé',
    category_detail: 'M-PLAC-SUB',
    recodedFunction: 'Magistrat placé SUB',
    rank: 6,
  },
  {
    category_label: 'Magistrat',
    label: 'JUGE PLACÉ',
    code: 'JP ADDITIONNEL',
    position: 'Placé',
    category_detail: 'M-PLAC-ADD',
    recodedFunction: 'Magistrat placé ADD',
    rank: 7,
  },
  {
    category_label: 'Magistrat',
    label: 'JUGE PLACÉ',
    code: 'JP SUBSTITUTION',
    position: 'Placé',
    category_detail: 'M-PLAC-SUB',
    recodedFunction: 'Magistrat placé SUB',
    rank: 7,
  },
  {
    category_label: 'Greffe',
    label: 'A PLACÉ',
    code: 'A PLACÉ ADDITIONNEL',
    position: 'Placé',
    category_detail: 'F-PLAC-ADD',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé ADD',
    rank: 11,
  },
  {
    category_label: 'Greffe',
    label: 'A PLACÉ',
    code: 'A PLACÉ SUBSTITUTION',
    position: 'Placé',
    category_detail: 'F-PLAC-SUB',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé SUB',
    rank: 11,
  },
  {
    category_label: 'Greffe',
    label: 'B GREFFIER PLACÉ',
    code: 'B GREF PLACÉ ADDITIONNEL',
    position: 'Placé',
    category_detail: 'F-PLAC-ADD',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé ADD',
    rank: 12,
  },
  {
    category_label: 'Greffe',
    label: 'B GREFFIER PLACÉ',
    code: 'B GREF PLACÉ SUBSTITUTION',
    position: 'Placé',
    category_detail: 'F-PLAC-SUB',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé SUB',
    rank: 12,
  },
  {
    category_label: 'Greffe',
    label: 'B PLACÉ',
    code: 'B PLACÉ ADDITIONNEL',
    position: 'Placé',
    category_detail: 'F-PLAC-ADD',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé ADD',
    rank: 13,
  },
  {
    category_label: 'Greffe',
    label: 'B PLACÉ',
    code: 'B PLACÉ SUBSTITUTION',
    position: 'Placé',
    category_detail: 'F-PLAC-SUB',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé SUB',
    rank: 13,
  },
  {
    category_label: 'Greffe',
    label: 'CB PLACÉ',
    code: 'CB PLACÉ ADDITIONNEL',
    position: 'Placé',
    category_detail: 'F-PLAC-ADD',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé ADD',
    rank: 14,
  },
  {
    category_label: 'Greffe',
    label: 'CB PLACÉ',
    code: 'CB PLACÉ SUBSTITUTION',
    position: 'Placé',
    category_detail: 'F-PLAC-SUB',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé SUB',
    rank: 14,
  },
  {
    category_label: 'Greffe',
    label: 'CT PLACÉ',
    code: 'CT PLACÉ ADDITIONNEL',
    position: 'Placé',
    category_detail: 'F-PLAC-ADD',
    recodedFunction: 'Fonctionnaire CTECH placé ADD',
    rank: 15,
  },
  {
    category_label: 'Greffe',
    label: 'CT PLACÉ',
    code: 'CT PLACÉ SUBSTITUTION',
    position: 'Placé',
    category_detail: 'F-PLAC-SUB',
    recodedFunction: 'Fonctionnaire CTECH placé SUB',
    rank: 15,
  },
  {
    // JA
    category_label: 'Autour du magistrat',
    label: 'JURISTE ASSISTANT pôle Social',
    code: 'JA Social',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ Social',
    rank: 3,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'JURISTE ASSISTANT Siège autres',
    code: 'JA Siège autres',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ Siège autres',
    rank: 3,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'JURISTE ASSISTANT Parquet',
    code: 'JA Parquet',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ Parquet',
    rank: 3,
  },

  {
    // CONT A JP
    category_label: 'Autour du magistrat',
    label: 'CONTRACTUEL A JUSTICE DE PROXIMITE',
    code: 'CONT A JP Siège',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'CONT A JP Siège',
    rank: 5,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'CONTRACTUEL A JUSTICE DE PROXIMITE',
    code: 'CONT A JP Parquet',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'CONT A JP Parquet',
    rank: 5,
  },
  {
    category_label: 'Greffe',
    label: 'CONTRACTUEL A JUSTICE DE PROXIMITE',
    code: 'CONT A JP Siège',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'CONT A JP Siège',
    rank: 23,
  },
  {
    category_label: 'Greffe',
    label: 'CONTRACTUEL A JUSTICE DE PROXIMITE',
    code: 'CONT A JP Parquet',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'CONT A JP Parquet',
    rank: 23,
  },
  {
    //CONT A
    category_label: 'Greffe',
    label: 'CONTRACTUEL A',
    code: 'CONT A VIF Siège',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'CONT A VIF Siège',
    rank: 17,
  },
  {
    category_label: 'Greffe',
    label: 'CONTRACTUEL A',
    code: 'CONT A VIF Parquet',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'CONT A VIF Parquet',
    rank: 17,
  },
  {
    category_label: 'Greffe',
    label: 'CONTRACTUEL A',
    code: 'CONT A Autres',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'Fonctionnaire A-B-CBUR',
    rank: 17,
  },
  // Att. Justice
  {
    category_label: 'Autour du magistrat',
    label: 'ATTACHÉ DE JUSTICE JA Siège autres',
    code: 'Att. J Siège autres',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ Siège autres',
    rank: 2,
  },
  {
    category_label: 'Autour du magistrat',
    label: 'ATTACHÉ DE JUSTICE Parquet',
    code: 'Att. J Parquet',
    position: 'Contractuel',
    category_detail: 'C',
    recodedFunction: 'JA/AttJ Parquet',
    rank: 2,
  },
  {
    category_label: 'Greffe',
    label: 'DSGJ PLACÉ ADDITIONNEL',
    code: 'DSGJ PLACÉ ADDITIONNEL',
    rank: 10,
    position: 'Placé',
    category_detail: 'F-PLAC-ADD',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé ADD',
  },
  {
    category_label: 'Greffe',
    label: 'DSGJ PLACÉ SUBSTITUTION',
    code: 'DSGJ PLACÉ SUBSTITUTION',
    rank: 10,
    position: 'Placé',
    category_detail: 'F-PLAC-SUB',
    recodedFunction: 'Fonctionnaire A-B-CBUR placé SUB',
  },
]
