export const JURIDICTION_BACKUP_ID = 16//74//5
export const JURIDICTION_OPTION_BACKUP_ID = 69
export const SOCIAL_LITIGATION_ID = 447
export const JURIDICTION_DATA_BACKUP_ID = 16
export const JURIDICTION_TEST_NAME = "24fb8bb550"