export const USER_TEST_EMAIL = 'test@mail.com'
export const USER_TEST_PASSWORD = 'test!t@ssworddifficult'
export const USER_TEST_FIRSTNAME = 'userTest'
export const USER_TEST_LASTNAME = 'userTest'
export const USER_TEST_FONCTION = 'Vacataire'
