export const HELP_START = 400
export const HELP_STOP = 401
export const HELP_AUTOSTART = 402
export const HELP_AUTOSTART_AND_STOP = 403

export const START_DATE_SIMULATOR = 350
export const END_DATE_SIMULATOR = 351
export const DATE_REAFECTATOR = 352
export const DATE_WHITE_SIMULATOR = 353

export const ACTIVITIES_SHOW_LEVEL_4 = 502

export const EXECUTE_CALCULATOR = 301
export const EXECUTE_CALCULATOR_CHANGE_DATE = 3011
export const CALCULATOR_SELECT_GREFFE = 3012
export const CALCULATOR_OPEN_CONTENTIEUX = 3013
export const CALCULATOR_OPEN_CONMPARAISON_RANGE = 3014
export const CALCULATOR_OPEN_CONMPARAISON_REFERENTIEL = 3015
export const CALCULATOR_OPEN_CHARTS_VIEW = 3016
export const CALCULATOR_OPEN_DETAILS_IN_CHARTS_VIEW = 3017


