spec:
  - 'test/index.test.js'
timeout: 60000
color: true
require: '@babel/register'
bail: false
reporter: 'mochawesome'
reporter-option:
  - reportDir=/home/api/test/reports
  - reportFilename=test-results
  - html=true
  - json=true
  - overwrite=true
  - quiet=false
  - charts=true
  - code=false
